language: java
jdk:
  - openjdk8
script:
  - gradle build
before_deploy:
  - mv build/libs/ROOT.war ROOT.war
  - zip deploy.zip ROOT.war
  - zip -u deploy.zip scripts/*
  - zip -u deploy.zip appspec.yml
  - test -d result || mkdir result
  - mv deploy.zip result/
deploy:
  - provider: s3
    bucket: lab-online-bucket
    access_key_id: $ACCESS_KEY_ID
    secret_access_key:
      secure: $SECRET_ACCESS_KEY
    local_dir: results
    skip_cleanup: true
    region: ap-northeast-1
    on:
      branch: master
