version: 0.0
os: linux
files:
  - source: ROOT.war
    destination: /var/lib/tomcat8/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop-service.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/delete.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start-service.sh
      timeout: 3600
